name: CrossCraft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:

  PSP:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
      - name: Install dependencies
        run: |
          apk add bash cmake git gmp mpc1 mpfr4 make
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          git config --global --add safe.directory /__w/CrossCraft-Edit/CrossCraft-Edit
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make
          cd ..
          mv build/EBOOT.PBP EBOOT.PBP
          mv build/CrossCraft-Classic.prx CrossCraft-Classic.prx
          mv texturepacks/default.zip default.zip
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CrossCraft-PSP
          path: |
            EBOOT.PBP
            CrossCraft-Classic.prx
            default.zip
            LICENSE
            README.md
            config.cfg

  Vita:
    runs-on: ubuntu-latest
    container: iridescentrose/psvitadev:latest
    
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build
        run: |
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          git config --global --add safe.directory /__w/CrossCraft-Classic/CrossCraft-Classic
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake -DVITA=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake ..
          make
          cd ..
          mv build/CrossCraft-Classic.vpk CrossCraft-Classic.vpk
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CrossCraft-Vita
          path: |
            CrossCraft-Classic.vpk
            LICENSE
            README.md

